spring.application.name=authservice

server.port=8081
secret.key ="z0rV7IK0R7MuWo70kRxJpxmd9zI2AnproZ17KbOYg3e"

spring.datasource.url= jdbc:mysql://192.168.1.10:3307/auth_service_db
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=password


spring.kafka.producer.bootstrap-servers =192.168.1.10:9092
spring.kafka.producer.key-serializer =org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer =com.codeartist.authservice.serializer.EventValueSerializer